from __future__ import annotations

from dataclasses import dataclass
from typing import List, Tuple


@dataclass
class Trace:
    """Holds trajectories generated by SMC for learning.

    Shapes mirror the Go trace:
      States[step][particle] = (x,y)
      Actions[step][particle] = int
      Rewards[step][particle] = float
      Proposed[step][particle] = bool
      Resampled[step] = bool
      Temp = float
    """
    nsteps: int
    nparticles: int
    states: List[List[Tuple[float, float]]]
    actions: List[List[int]]
    rewards: List[List[float]]
    proposed: List[List[bool]]
    resampled: List[bool]
    temp: float = 1.0

    @classmethod
    def new(cls, nsteps: int, nparticles: int) -> "Trace":
        states = [[(0.0, 0.0) for _ in range(nparticles)] for __ in range(nsteps)]
        actions = [[0 for _ in range(nparticles)] for __ in range(nsteps)]
        rewards = [[0.0 for _ in range(nparticles)] for __ in range(nsteps)]
        proposed = [[False for _ in range(nparticles)] for __ in range(nsteps)]
        resampled = [False for _ in range(nsteps)]
        return cls(nsteps, nparticles, states, actions, rewards, proposed, resampled)
